Traceback (most recent call last):
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Hannah Luebbering\.conda\envs\cse160\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Split train/test
X_train, X_test, y_train, y_test = member_train_test_split(data)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36m_transform_general[1;34m(self, func, *args, **kwargs)[0m
[0;32m   1316[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1317[1;33m                 [0mpath[0m[1;33m,[0m [0mres[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_choose_path[0m[1;33m([0m[0mfast_path[0m[1;33m,[0m [0mslow_path[0m[1;33m,[0m [0mgroup[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1318[0m             [1;32mexcept[0m [0mTypeError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36m_choose_path[1;34m(self, fast_path, slow_path, group)[0m
[0;32m   1393[0m         [0mpath[0m [1;33m=[0m [0mslow_path[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1394[1;33m         [0mres[0m [1;33m=[0m [0mslow_path[0m[1;33m([0m[0mgroup[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1395[0m [1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36m<lambda>[1;34m(group)[0m
[0;32m   1382[0m             slow_path = lambda group: group.apply(
[1;32m-> 1383[1;33m                 [1;32mlambda[0m [0mx[0m[1;33m:[0m [0mgetattr[0m[1;33m([0m[0mx[0m[1;33m,[0m [0mfunc[0m[1;33m)[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0maxis[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1384[0m             )

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\frame.py[0m in [0;36mapply[1;34m(self, func, axis, raw, result_type, args, **kwargs)[0m
[0;32m   8739[0m         )
[1;32m-> 8740[1;33m         [1;32mreturn[0m [0mop[0m[1;33m.[0m[0mapply[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   8741[0m [1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\apply.py[0m in [0;36mapply[1;34m(self)[0m
[0;32m    687[0m [1;33m[0m[0m
[1;32m--> 688[1;33m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mapply_standard[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    689[0m [1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\apply.py[0m in [0;36mapply_standard[1;34m(self)[0m
[0;32m    811[0m     [1;32mdef[0m [0mapply_standard[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 812[1;33m         [0mresults[0m[1;33m,[0m [0mres_index[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mapply_series_generator[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    813[0m [1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\apply.py[0m in [0;36mapply_series_generator[1;34m(self)[0m
[0;32m    827[0m                 [1;31m# ignore SettingWithCopy here in case the user mutates[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 828[1;33m                 [0mresults[0m[1;33m[[0m[0mi[0m[1;33m][0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mf[0m[1;33m([0m[0mv[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    829[0m                 [1;32mif[0m [0misinstance[0m[1;33m([0m[0mresults[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m,[0m [0mABCSeries[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36m<lambda>[1;34m(x)[0m
[0;32m   1382[0m             slow_path = lambda group: group.apply(
[1;32m-> 1383[1;33m                 [1;32mlambda[0m [0mx[0m[1;33m:[0m [0mgetattr[0m[1;33m([0m[0mx[0m[1;33m,[0m [0mfunc[0m[1;33m)[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0maxis[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1384[0m             )

[1;31mTypeError[0m: 'int' object is not callable

During handling of the above exception, another exception occurred:

[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32mC:\conda_tmp\ipykernel_23096\731815928.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Split train/test[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mX_train[0m[1;33m,[0m [0mX_test[0m[1;33m,[0m [0my_train[0m[1;33m,[0m [0my_test[0m [1;33m=[0m [0mmember_train_test_split[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mprint[0m[1;33m([0m[0mX_train[0m[1;33m.[0m[0mshape[0m[1;33m,[0m [0my_train[0m[1;33m.[0m[0mshape[0m[1;33m,[0m [0mX_test[0m[1;33m.[0m[0mshape[0m[1;33m,[0m [0my_test[0m[1;33m.[0m[0mshape[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\conda_tmp\ipykernel_23096\48851854.py[0m in [0;36mmember_train_test_split[1;34m(df, test_size)[0m
[0;32m      6[0m     [0mtrain_size[0m [1;33m=[0m [1;33m([0m[1;36m1[0m [1;33m-[0m [0mtest_size[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m     [0mg[0m [1;33m=[0m [0mdf[0m[1;33m.[0m[0mgroupby[0m[1;33m([0m[1;34m'memberID'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 8[1;33m     [0mtrain_flags[0m [1;33m=[0m [1;33m([0m[0mg[0m[1;33m.[0m[0mcumcount[0m[1;33m([0m[1;33m)[0m [1;33m+[0m [1;36m1[0m[1;33m)[0m [1;33m<=[0m [0mg[0m[1;33m.[0m[0mtransform[0m[1;33m([0m[1;34m'size'[0m[1;33m)[0m [1;33m*[0m [0mtrain_size[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      9[0m     [0mtest_flags[0m [1;33m=[0m [1;33m([0m[0mg[0m[1;33m.[0m[0mcumcount[0m[1;33m([0m[1;33m)[0m [1;33m+[0m [1;36m1[0m[1;33m)[0m [1;33m>[0m [0mg[0m[1;33m.[0m[0mtransform[0m[1;33m([0m[1;34m'size'[0m[1;33m)[0m [1;33m*[0m [0mtrain_size[0m[1;33m[0m[1;33m[0m[0m
[0;32m     10[0m [1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36mtransform[1;34m(self, func, engine, engine_kwargs, *args, **kwargs)[0m
[0;32m   1356[0m     [1;32mdef[0m [0mtransform[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mfunc[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m,[0m [0mengine[0m[1;33m=[0m[1;32mNone[0m[1;33m,[0m [0mengine_kwargs[0m[1;33m=[0m[1;32mNone[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1357[0m         return self._transform(
[1;32m-> 1358[1;33m             [0mfunc[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m,[0m [0mengine[0m[1;33m=[0m[0mengine[0m[1;33m,[0m [0mengine_kwargs[0m[1;33m=[0m[0mengine_kwargs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1359[0m         )
[0;32m   1360[0m [1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\groupby.py[0m in [0;36m_transform[1;34m(self, func, engine, engine_kwargs, *args, **kwargs)[0m
[0;32m   1468[0m [1;33m[0m[0m
[0;32m   1469[0m             [1;31m# only reached for DataFrameGroupBy[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1470[1;33m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_transform_general[0m[1;33m([0m[0mfunc[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1471[0m [1;33m[0m[0m
[0;32m   1472[0m     [1;31m# -----------------------------------------------------------------[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36m_transform_general[1;34m(self, func, *args, **kwargs)[0m
[0;32m   1317[0m                 [0mpath[0m[1;33m,[0m [0mres[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_choose_path[0m[1;33m([0m[0mfast_path[0m[1;33m,[0m [0mslow_path[0m[1;33m,[0m [0mgroup[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1318[0m             [1;32mexcept[0m [0mTypeError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1319[1;33m                 [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_transform_item_by_item[0m[1;33m([0m[0mobj[0m[1;33m,[0m [0mfast_path[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1320[0m             [1;32mexcept[0m [0mValueError[0m [1;32mas[0m [0merr[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1321[0m                 [0mmsg[0m [1;33m=[0m [1;34m"transform must return a scalar value for each group"[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\cse160\lib\site-packages\pandas\core\groupby\generic.py[0m in [0;36m_transform_item_by_item[1;34m(self, obj, wrapper)[0m
[0;32m   1446[0m [1;33m[0m[0m
[0;32m   1447[0m         [1;32mif[0m [1;32mnot[0m [0moutput[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1448[1;33m             [1;32mraise[0m [0mTypeError[0m[1;33m([0m[1;34m"Transform function invalid for data types"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1449[0m [1;33m[0m[0m
[0;32m   1450[0m         [0mcolumns[0m [1;33m=[0m [0mobj[0m[1;33m.[0m[0mcolumns[0m[1;33m.[0m[0mtake[0m[1;33m([0m[0minds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: Transform function invalid for data types
TypeError: Transform function invalid for data types

